# Generated by Django 4.0.5 on 2022-07-19 12:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='user',
        ),
        migrations.AddField(
            model_name='blogs',
            name='roll_no',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='blogs',
            name='student_name',
            field=models.CharField(default='undefined', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
