# Generated by Django 4.0.5 on 2022-07-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_blogs_user_blogs_roll_no_blogs_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='flaged',
            field=models.BooleanField(default=False),
        ),
    ]
