# Generated by Django 4.0.5 on 2022-07-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_blogs_flaged'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='flagged_comment',
            field=models.CharField(default='Nil', max_length=300),
        ),
    ]
