# Generated by Django 4.0.5 on 2022-07-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blogs_flagged_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='innerHtml',
            field=models.TextField(default=''),
        ),
    ]
